import { CountryCode } from "./enums/countryCode";
import { CurrencyCode } from "./enums/currencyCode";

export class Country {
  readonly code: CountryCode;
  readonly name: string;
  readonly currency: CurrencyCode;

  constructor(name: string, code: CountryCode, currency: CurrencyCode) {
    this.name = name;
    this.code = code;
    this.currency = currency;
  }
}

export class Countries {
  static readonly AD: Country = new Country("Andorra", CountryCode.AD, CurrencyCode.EUR);
  static readonly AF: Country = new Country("Afghanistan", CountryCode.AF, CurrencyCode.AFN);
  static readonly AG: Country = new Country("Antigua and Barbuda", CountryCode.AG, CurrencyCode.XCD);
  static readonly AI: Country = new Country("Anguilla", CountryCode.AI, CurrencyCode.XCD);
  static readonly AL: Country = new Country("Albania", CountryCode.AL, CurrencyCode.ALL);
  static readonly AM: Country = new Country("Armenia", CountryCode.AM, CurrencyCode.AMD);
  static readonly AO: Country = new Country("Angola", CountryCode.AO, CurrencyCode.AOA);
  static readonly AR: Country = new Country("Argentina", CountryCode.AR, CurrencyCode.ARS);
  static readonly AS: Country = new Country("American Samoa", CountryCode.AS, CurrencyCode.USD);
  static readonly AT: Country = new Country("Austria", CountryCode.AT, CurrencyCode.EUR);
  static readonly AU: Country = new Country("Australia", CountryCode.AU, CurrencyCode.AUD);
  static readonly AW: Country = new Country("Aruba", CountryCode.AW, CurrencyCode.AWG);
  static readonly AX: Country = new Country("Åland Islands", CountryCode.AX, CurrencyCode.EUR);
  static readonly AZ: Country = new Country("Azerbaijan", CountryCode.AZ, CurrencyCode.AZN);
  static readonly BA: Country = new Country("Bosnia and Herzegovina", CountryCode.BA, CurrencyCode.BAM);
  static readonly BB: Country = new Country("Barbados", CountryCode.BB, CurrencyCode.BBD);
  static readonly BD: Country = new Country("Bangladesh", CountryCode.BD, CurrencyCode.BDT);
  static readonly BE: Country = new Country("Belgium", CountryCode.BE, CurrencyCode.EUR);
  static readonly BF: Country = new Country("Burkina Faso", CountryCode.BF, CurrencyCode.XOF);
  static readonly BG: Country = new Country("Bulgaria", CountryCode.BG, CurrencyCode.BGN);
  static readonly BI: Country = new Country("Burundi", CountryCode.BI, CurrencyCode.BIF);
  static readonly BJ: Country = new Country("Benin", CountryCode.BJ, CurrencyCode.XOF);
  static readonly BL: Country = new Country("Saint Barthélemy", CountryCode.BL, CurrencyCode.EUR);
  static readonly BM: Country = new Country("Bermuda", CountryCode.BM, CurrencyCode.BMD);
  static readonly BN: Country = new Country("Brunei Darussalam", CountryCode.BN, CurrencyCode.BND);
  static readonly BO: Country = new Country("Bolivia (Plurinational State of)", CountryCode.BO, CurrencyCode.BOP);
  static readonly BQ: Country = new Country("Bonaire, Sint Eustatius and Saba", CountryCode.BQ, CurrencyCode.USD);
  static readonly BR: Country = new Country("Brazil", CountryCode.BR, CurrencyCode.BRL);
  static readonly BV: Country = new Country("Bouvet Island", CountryCode.BV, CurrencyCode.NOK);
  static readonly BW: Country = new Country("Botswana", CountryCode.BW, CurrencyCode.BWP);
  static readonly BY: Country = new Country("Belarus", CountryCode.BY, CurrencyCode.BYR);
  static readonly BZ: Country = new Country("Belize", CountryCode.BZ, CurrencyCode.BZD);
  static readonly CA: Country = new Country("Canada", CountryCode.CA, CurrencyCode.CAD);
  static readonly CH: Country = new Country("Switzerland", CountryCode.CH, CurrencyCode.CHF);
  static readonly CI: Country = new Country("Côte d'Ivoire", CountryCode.CI, CurrencyCode.XOF);
  static readonly CL: Country = new Country("Chile", CountryCode.CL, CurrencyCode.CLP);
  static readonly CM: Country = new Country("Cameroon", CountryCode.CM, CurrencyCode.XAF);
  static readonly CN: Country = new Country("China", CountryCode.CN, CurrencyCode.CNY);
  static readonly CO: Country = new Country("Colombia", CountryCode.CO, CurrencyCode.COP);
  static readonly CR: Country = new Country("Costa Rica", CountryCode.CR, CurrencyCode.CRC);
  static readonly CV: Country = new Country("Cabo Verde", CountryCode.CV, CurrencyCode.CVE);
  static readonly CW: Country = new Country("Curaçao", CountryCode.CW, CurrencyCode.ANG);
  static readonly CX: Country = new Country("Christmas Island", CountryCode.CX, CurrencyCode.AUD);
  static readonly CY: Country = new Country("Cyprus", CountryCode.CY, CurrencyCode.EUR);
  static readonly DE: Country = new Country("Germany", CountryCode.DE, CurrencyCode.EUR);
  static readonly DJ: Country = new Country("Djibouti", CountryCode.DJ, CurrencyCode.DJF);
  static readonly DK: Country = new Country("Denmark", CountryCode.DK, CurrencyCode.DKK);
  static readonly DM: Country = new Country("Dominica", CountryCode.DM, CurrencyCode.XCD);
  static readonly DZ: Country = new Country("Algeria", CountryCode.DZ, CurrencyCode.DZD);
  static readonly EC: Country = new Country("Ecuador", CountryCode.EC, CurrencyCode.USD);
  static readonly EE: Country = new Country("Estonia", CountryCode.EE, CurrencyCode.EUR);
  static readonly EG: Country = new Country("Egypt", CountryCode.EG, CurrencyCode.EGP);
  static readonly EH: Country = new Country("Western Sahara", CountryCode.EH, CurrencyCode.MAD);
  static readonly ES: Country = new Country("Spain", CountryCode.ES, CurrencyCode.EUR);
  static readonly ET: Country = new Country("Ethiopia", CountryCode.ET, CurrencyCode.ETB);
  static readonly FI: Country = new Country("Finland", CountryCode.FI, CurrencyCode.EUR);
  static readonly FJ: Country = new Country("Fiji", CountryCode.FJ, CurrencyCode.FJD);
  static readonly FM: Country = new Country("Micronesia (Federated States of)", CountryCode.FM, CurrencyCode.USD);
  static readonly FR: Country = new Country("France", CountryCode.FR, CurrencyCode.EUR);
  static readonly GA: Country = new Country("Gabon", CountryCode.GA, CurrencyCode.XAF);
  static readonly GD: Country = new Country("Grenada", CountryCode.GD, CurrencyCode.XCD);
  static readonly GE: Country = new Country("Georgia", CountryCode.GE, CurrencyCode.GEL);
  static readonly GF: Country = new Country("French Guiana", CountryCode.GF, CurrencyCode.EUR);
  static readonly GG: Country = new Country("Guernsey", CountryCode.GG, CurrencyCode.GBP);
  static readonly GI: Country = new Country("Gibraltar", CountryCode.GI, CurrencyCode.GIP);
  static readonly GL: Country = new Country("Greenland", CountryCode.GL, CurrencyCode.DKK);
  static readonly GN: Country = new Country("Guinea", CountryCode.GN, CurrencyCode.GNF);
  static readonly GP: Country = new Country("Guadeloupe", CountryCode.GP, CurrencyCode.EUR);
  static readonly GQ: Country = new Country("Equatorial Guinea", CountryCode.GQ, CurrencyCode.XAF);
  static readonly GR: Country = new Country("Greece", CountryCode.GR, CurrencyCode.EUR);
  static readonly GT: Country = new Country("Guatemala", CountryCode.GT, CurrencyCode.GTQ);
  static readonly GU: Country = new Country("Guam", CountryCode.GU, CurrencyCode.USD);
  static readonly GW: Country = new Country("Guinea-Bissau", CountryCode.GW, CurrencyCode.XOF);
  static readonly GY: Country = new Country("Guyana", CountryCode.GY, CurrencyCode.GYD);
  static readonly HK: Country = new Country("Hong Kong", CountryCode.HK, CurrencyCode.HKD);
  static readonly HN: Country = new Country("Honduras", CountryCode.HN, CurrencyCode.HNL);
  static readonly HR: Country = new Country("Croatia", CountryCode.HR, CurrencyCode.HRK);
  static readonly HT: Country = new Country("Haiti", CountryCode.HT, CurrencyCode.HTG);
  static readonly HU: Country = new Country("Hungary", CountryCode.HU, CurrencyCode.HUF);
  static readonly ID: Country = new Country("Indonesia", CountryCode.ID, CurrencyCode.IDR);
  static readonly IE: Country = new Country("Ireland", CountryCode.IE, CurrencyCode.EUR);
  static readonly IL: Country = new Country("Israel", CountryCode.IL, CurrencyCode.ILS);
  static readonly IM: Country = new Country("Isle of Man", CountryCode.IM, CurrencyCode.GBP);
  static readonly IN: Country = new Country("India", CountryCode.IN, CurrencyCode.INR);
  static readonly IS: Country = new Country("Iceland", CountryCode.IS, CurrencyCode.ISK);
  static readonly IT: Country = new Country("Italy", CountryCode.IT, CurrencyCode.EUR);
  static readonly JE: Country = new Country("Jersey", CountryCode.JE, CurrencyCode.GBP);
  static readonly JM: Country = new Country("Jamaica", CountryCode.JM, CurrencyCode.JMD);
  static readonly JP: Country = new Country("Japan", CountryCode.JP, CurrencyCode.JPY);
  static readonly KE: Country = new Country("Kenya", CountryCode.KE, CurrencyCode.KES);
  static readonly KG: Country = new Country("Kyrgyzstan", CountryCode.KG, CurrencyCode.KGS);
  static readonly KH: Country = new Country("Cambodia", CountryCode.KH, CurrencyCode.KHR);
  static readonly KR: Country = new Country("South Korea", CountryCode.KR, CurrencyCode.KRW);
  static readonly KI: Country = new Country("Kiribati", CountryCode.KI, CurrencyCode.AUD);
  static readonly KN: Country = new Country("Saint Kitts and Nevis", CountryCode.KN, CurrencyCode.XCD);
  static readonly KZ: Country = new Country("Kazakhstan", CountryCode.KZ, CurrencyCode.KZT);
  static readonly LB: Country = new Country("Lebanon", CountryCode.LB, CurrencyCode.LBP);
  static readonly LC: Country = new Country("Saint Lucia", CountryCode.LC, CurrencyCode.XCD);
  static readonly LI: Country = new Country("Liechtenstein", CountryCode.LI, CurrencyCode.CHF);
  static readonly LK: Country = new Country("Sri Lanka", CountryCode.LK, CurrencyCode.LKR);
  static readonly LR: Country = new Country("Liberia", CountryCode.LR, CurrencyCode.LRD);
  static readonly LS: Country = new Country("Lesotho", CountryCode.LS, CurrencyCode.LSL);
  static readonly LT: Country = new Country("Lithuania", CountryCode.LT, CurrencyCode.EUR);
  static readonly LU: Country = new Country("Luxembourg", CountryCode.LU, CurrencyCode.EUR);
  static readonly LV: Country = new Country("Latvia", CountryCode.LV, CurrencyCode.EUR);
  static readonly MA: Country = new Country("Morocco", CountryCode.MA, CurrencyCode.MAD);
  static readonly MC: Country = new Country("Monaco", CountryCode.MC, CurrencyCode.EUR);
  static readonly ME: Country = new Country("Montenegro", CountryCode.ME, CurrencyCode.EUR);
  static readonly MF: Country = new Country("Saint Martin (French part)", CountryCode.MF, CurrencyCode.EUR);
  static readonly MG: Country = new Country("Madagascar", CountryCode.MG, CurrencyCode.MGA);
  static readonly ML: Country = new Country("Mali", CountryCode.ML, CurrencyCode.XOF);
  static readonly MM: Country = new Country("Myanmar", CountryCode.MM, CurrencyCode.MMK);
  static readonly MN: Country = new Country("Mongolia", CountryCode.MN, CurrencyCode.MNT);
  static readonly MO: Country = new Country("Macao", CountryCode.MO, CurrencyCode.MOP);
  static readonly MQ: Country = new Country("Martinique", CountryCode.MQ, CurrencyCode.EUR);
  static readonly MS: Country = new Country("Montserrat", CountryCode.MS, CurrencyCode.XCD);
  static readonly MT: Country = new Country("Malta", CountryCode.MT, CurrencyCode.EUR);
  static readonly MU: Country = new Country("Mauritius", CountryCode.MU, CurrencyCode.MUR);
  static readonly MV: Country = new Country("Maldives", CountryCode.MV, CurrencyCode.MVR);
  static readonly MW: Country = new Country("Malawi", CountryCode.MW, CurrencyCode.MWK);
  static readonly MX: Country = new Country("Mexico", CountryCode.MX, CurrencyCode.MXN);
  static readonly MY: Country = new Country("Malaysia", CountryCode.MY, CurrencyCode.MYR);
  static readonly MZ: Country = new Country("Mozambique", CountryCode.MZ, CurrencyCode.MZN);
  static readonly NA: Country = new Country("Namibia", CountryCode.NA, CurrencyCode.NAD);
  static readonly NC: Country = new Country("New Caledonia", CountryCode.NC, CurrencyCode.XPF);
  static readonly NF: Country = new Country("Norfolk Island", CountryCode.NF, CurrencyCode.AUD);
  static readonly NG: Country = new Country("Nigeria", CountryCode.NG, CurrencyCode.NGN);
  static readonly NI: Country = new Country("Nicaragua", CountryCode.NI, CurrencyCode.NIO);
  static readonly NO: Country = new Country("Norway", CountryCode.NO, CurrencyCode.NOK);
  static readonly NP: Country = new Country("Nepal", CountryCode.NP, CurrencyCode.NPR);
  static readonly NR: Country = new Country("Nauru", CountryCode.NR, CurrencyCode.AUD);
  static readonly NU: Country = new Country("Niue", CountryCode.NU, CurrencyCode.NZD);
  static readonly NZ: Country = new Country("New Zealand", CountryCode.NZ, CurrencyCode.NZD);
  static readonly PA: Country = new Country("Panama", CountryCode.PA, CurrencyCode.PAB);
  static readonly PE: Country = new Country("Peru", CountryCode.PE, CurrencyCode.PEN);
  static readonly PF: Country = new Country("French Polynesia", CountryCode.PF, CurrencyCode.XPF);
  static readonly PG: Country = new Country("Papua New Guinea", CountryCode.PG, CurrencyCode.PGK);
  static readonly PK: Country = new Country("Pakistan", CountryCode.PK, CurrencyCode.PKR);
  static readonly PL: Country = new Country("Poland", CountryCode.PL, CurrencyCode.PLN);
  static readonly PM: Country = new Country("Saint Pierre and Miquelon", CountryCode.PM, CurrencyCode.EUR);
  static readonly PN: Country = new Country("Pitcairn", CountryCode.PN, CurrencyCode.NZD);
  static readonly PR: Country = new Country("Puerto Rico", CountryCode.PR, CurrencyCode.USD);
  static readonly PT: Country = new Country("Portugal", CountryCode.PT, CurrencyCode.EUR);
  static readonly PW: Country = new Country("Palau", CountryCode.PW, CurrencyCode.USD);
  static readonly PY: Country = new Country("Paraguay", CountryCode.PY, CurrencyCode.PYG);
  static readonly QA: Country = new Country("Qatar", CountryCode.QA, CurrencyCode.QAR);
  static readonly RE: Country = new Country("Réunion", CountryCode.RE, CurrencyCode.EUR);
  static readonly RO: Country = new Country("Romania", CountryCode.RO, CurrencyCode.RON);
  static readonly RS: Country = new Country("Serbia", CountryCode.RS, CurrencyCode.RSD);
  static readonly RU: Country = new Country("Russia", CountryCode.RU, CurrencyCode.RUB);
  static readonly RW: Country = new Country("Rwanda", CountryCode.RW, CurrencyCode.RWF);
  static readonly SA: Country = new Country("Saudi Arabia", CountryCode.SA, CurrencyCode.SAR);
  static readonly SB: Country = new Country("Solomon Islands", CountryCode.SB, CurrencyCode.SBD);
  static readonly SC: Country = new Country("Seychelles", CountryCode.SC, CurrencyCode.SCR);
  static readonly SE: Country = new Country("Sweden", CountryCode.SE, CurrencyCode.SEK);
  static readonly SG: Country = new Country("Singapore", CountryCode.SG, CurrencyCode.SGD);
  static readonly SH: Country = new Country("Saint Helena, Ascension and Tristan da Cunha", CountryCode.SH, CurrencyCode.SHP);
  static readonly SI: Country = new Country("Slovenia", CountryCode.SI, CurrencyCode.EUR);
  static readonly SJ: Country = new Country("Svalbard and Jan Mayen", CountryCode.SJ, CurrencyCode.NOK);
  static readonly SK: Country = new Country("Slovakia", CountryCode.SK, CurrencyCode.EUR);
  static readonly SL: Country = new Country("Sierra Leone", CountryCode.SL, CurrencyCode.SLL);
  static readonly SM: Country = new Country("San Marino", CountryCode.SM, CurrencyCode.EUR);
  static readonly SN: Country = new Country("Senegal", CountryCode.SN, CurrencyCode.XOF);
  static readonly SO: Country = new Country("Somalia", CountryCode.SO, CurrencyCode.SOS);
  static readonly SR: Country = new Country("Suriname", CountryCode.SR, CurrencyCode.SRD);
  static readonly SX: Country = new Country("Sint Maarten (Dutch part)", CountryCode.SX, CurrencyCode.ANG);
  static readonly TD: Country = new Country("Chad", CountryCode.TD, CurrencyCode.XAF);
  static readonly TG: Country = new Country("Togo", CountryCode.TG, CurrencyCode.XOF);
  static readonly TH: Country = new Country("Thailand", CountryCode.TH, CurrencyCode.THB);
  static readonly TJ: Country = new Country("Tajikistan", CountryCode.TJ, CurrencyCode.TJS);
  static readonly TK: Country = new Country("Tokelau", CountryCode.TK, CurrencyCode.NZD);
  static readonly TL: Country = new Country("Timor-Leste", CountryCode.TL, CurrencyCode.USD);
  static readonly TO: Country = new Country("Tonga", CountryCode.TO, CurrencyCode.TOP);
  static readonly TR: Country = new Country("Turkey", CountryCode.TR, CurrencyCode.TRY);
  static readonly TT: Country = new Country("Trinidad and Tobago", CountryCode.TT, CurrencyCode.TTD);
  static readonly TV: Country = new Country("Tuvalu", CountryCode.TV, CurrencyCode.AUD);
  static readonly TZ: Country = new Country("United Republic of Tanzania", CountryCode.TZ, CurrencyCode.TZS);
  static readonly UA: Country = new Country("Ukraine", CountryCode.UA, CurrencyCode.UAH);
  static readonly UG: Country = new Country("Uganda", CountryCode.UG, CurrencyCode.UGX);
  static readonly US: Country = new Country("United States of America", CountryCode.US, CurrencyCode.USD);
  static readonly UY: Country = new Country("Uruguay", CountryCode.UY, CurrencyCode.UYU);
  static readonly UZ: Country = new Country("Uzbekistan", CountryCode.UZ, CurrencyCode.UZS);
  static readonly VC: Country = new Country("Saint Vincent and the Grenadines", CountryCode.VC, CurrencyCode.XCD);
  static readonly VG: Country = new Country("Virgin Islands (British)", CountryCode.VG, CurrencyCode.USD);
  static readonly VI: Country = new Country("Virgin Islands (U.S.)", CountryCode.VI, CurrencyCode.USD);
  static readonly VN: Country = new Country("Vietnam", CountryCode.VN, CurrencyCode.VND);
  static readonly VU: Country = new Country("Vanuatu", CountryCode.VU, CurrencyCode.VUV);
  static readonly WF: Country = new Country("Wallis and Futuna", CountryCode.WF, CurrencyCode.XPF);
  static readonly WS: Country = new Country("Samoa", CountryCode.WS, CurrencyCode.WST);
  static readonly YE: Country = new Country("Yemen", CountryCode.YE, CurrencyCode.YER);
  static readonly YT: Country = new Country("Mayotte", CountryCode.YT, CurrencyCode.EUR);
  static readonly ZA: Country = new Country("South Africa", CountryCode.ZA, CurrencyCode.ZAR);
  static readonly ZM: Country = new Country("Zambia", CountryCode.ZM, CurrencyCode.ZMW);
  static readonly SZ: Country = new Country("Eswatini", CountryCode.SZ, CurrencyCode.SZL);
  static readonly MK: Country = new Country("North Macedonia", CountryCode.MK, CurrencyCode.MKD);
  static readonly PH: Country = new Country("Philippines", CountryCode.PH, CurrencyCode.PHP);
  static readonly NL: Country = new Country("Netherlands", CountryCode.NL, CurrencyCode.EUR);
  static readonly AE: Country = new Country("United Arab Emirates", CountryCode.AE, CurrencyCode.AED);
  static readonly MD: Country = new Country("Republic of Moldova", CountryCode.MD, CurrencyCode.MDL);
  static readonly GM: Country = new Country("Gambia", CountryCode.GM, CurrencyCode.GMD);
  static readonly DO: Country = new Country("Dominican Republic", CountryCode.DO, CurrencyCode.DOP);
  static readonly LA: Country = new Country("Lao People's Democratic Republic", CountryCode.LA, CurrencyCode.LAK);
  static readonly TW: Country = new Country("Taiwan, Province of China", CountryCode.TW, CurrencyCode.TWD);
  static readonly CG: Country = new Country("Republic of the Congo", CountryCode.CG, CurrencyCode.XAF);
  static readonly CZ: Country = new Country("Czechia", CountryCode.CZ, CurrencyCode.CZK);
  static readonly GB: Country = new Country("United Kingdom", CountryCode.GB, CurrencyCode.GBP);
  static readonly NE: Country = new Country("Niger", CountryCode.NE, CurrencyCode.XOF);
  static readonly CD: Country = new Country("Democratic Republic of the Congo", CountryCode.CD, CurrencyCode.CDF);
  static readonly BS: Country = new Country("Commonwealth of The Bahamas", CountryCode.BS, CurrencyCode.BSD);
  static readonly CC: Country = new Country("Cocos (Keeling) Islands", CountryCode.CC, CurrencyCode.AUD);
  static readonly CF: Country = new Country("Central African Republic", CountryCode.CF, CurrencyCode.XAF);
  static readonly CK: Country = new Country("Cook Islands", CountryCode.CK, CurrencyCode.NZD);
  static readonly FK: Country = new Country("Falkland Islands", CountryCode.FK, CurrencyCode.FKP);
  static readonly FO: Country = new Country("Faroe Islands", CountryCode.FO, CurrencyCode.DKK);
  static readonly HM: Country = new Country("Territory of Heard Island and McDonald Islands", CountryCode.HM, CurrencyCode.AUD);
  static readonly IO: Country = new Country("British Indian Ocean Territory", CountryCode.IO, CurrencyCode.USD);
  static readonly KM: Country = new Country("Comoros", CountryCode.KM, CurrencyCode.KMF);
  static readonly KY: Country = new Country("Cayman Islands", CountryCode.KY, CurrencyCode.KYD);
  static readonly MH: Country = new Country("Republic of the Marshall Islands", CountryCode.MH, CurrencyCode.USD);
  static readonly MP: Country = new Country("Commonwealth of the Northern Mariana Islands", CountryCode.MP, CurrencyCode.USD);
  static readonly TC: Country = new Country("Turks and Caicos Islands", CountryCode.TC, CurrencyCode.USD);
  static readonly TF: Country = new Country("French Southern and Antarctic Lands", CountryCode.TF, CurrencyCode.EUR);
  static readonly UM: Country = new Country("United States Minor Outlying Islands", CountryCode.UM, CurrencyCode.USD);
  static readonly VA: Country = new Country("Holy See", CountryCode.VA, CurrencyCode.EUR);


  static fromCode(code: string): Country | undefined {
    // @ts-ignore
    return Countries[code];
  }

  static getCurrency(code: string): CurrencyCode | undefined {
    const country = this.fromCode(code);
    if (country === undefined) return;
    return country.currency;
  }
}
